name: Run Tests on push to main

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  test_3_8:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest lorem
          pip install -r requirements.txt
          
      - name: Run Tests
        run: pytest
        env:
          WRANGLES_USER: ${{ secrets.WRANGLES_USER }}
          WRANGLES_PASSWORD: ${{ secrets.WRANGLES_PASSWORD }}

  test_3_9:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest lorem
          pip install -r requirements.txt
          
      - name: Run Tests
        run: pytest
        env:
          WRANGLES_USER: ${{ secrets.WRANGLES_USER }}
          WRANGLES_PASSWORD: ${{ secrets.WRANGLES_PASSWORD }}